backend:
  name: git-gateway
  branch: master

media_folder: "images/upload"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "subtitle", widget: "string"}
      - {label: "Publish", name: "published", widget: "boolean"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}